### PR TITLE
New preprocessing code

### PR DESCRIPTION
**Pull request by ksakash**
with improved detection code in the new_detection_code directory and extras code that i tried before applying them is in the extras directory .... line_detection code still needed to be improved

### CODE REVIEW

**Comment by Mayankm96** [comment]
Hi @ksakash!

Well I would say to reorganize your code into the right folders and name the files properly. There is no need to name then like `new_*`. Move the codes to the task layers and other places. Also there is an issue with tab spacing so fix that using the script [here](https://github.com/AUV-IITK/auv2017/blob/master/utils/format_cpp.sh). 

I would also say be more generous in commenting and also a readme file to your code as shown [here](https://github.com/Mayankm96/SOFT_odom/blob/master/README.md) would be good.

Make these changes and let me know. I'll review into each code after that. Also in the README share the link to the bag files you created and how to run your code with those bag files. 

Ciao! :)

PS: Create your README in the task layer where your code is. Not the main README. You made changes to that.

**Comment by Mayankm96** [comment]
Also I forgot to mention, refer to our [code style](https://github.com/AUV-IITK/AUVWiki/wiki/Developers-Guide)! :)

**Comment by ksakash** [comment]
@Mayankm96 , replaced all the detection code.
I will remove the tab issues but for now if you want to test the code just  ```catkin_make``` because the build.sh will give thousands of roslint errors.

**Comment by Mayankm96** [comment]
@ksakash nice work. I have reviewed your code and you should make the changes accordingly. Try to fix the roslint errors as well. 

We can discuss more once we are back. Also it would be useful if you could create a doc of the algorithm which we can use internally to see what we are doing.

**Comment by ksakash** [comment]
fixed roslint errors

**Comment by ksakash** [comment]
removed dynamic reconfiguration

**Pull request closed without merging**
