### PR TITLE
fixing bugs and controls

### PR DESCRIPTION
**Pull request by Suryansh470**

### CODE REVIEW

**Comment by Suryansh470** [comment]
these all are maintained by me and arnav...

**Comment by Mayankm96** [comment]
@Suryansh470 It's really hard to see what changes you have done since the entire auv2016 repo has been copied here. I would say, first copy that repo to auv2017 and put your first commit with the name `old repo`, after that cherrypick the commits made above to the branch.

**Comment by Mayankm96** [comment]
Also be verbose in your pull request as what exactly changes you have done.

**Comment by Suryansh470** [comment]
okay I will do it....

**Comment by pkhrag** [comment]
@Mayankm96 fork the auv16 repo here.. i can't do it, i dont have admin rights in auv17 :p. This coping and pasting code is pointless.. just fork it here so that all the commits can also be retrieved.

**Pull request closed without merging**
