### PR TITLE
Changes for Pixhawk and its documentation

### PR DESCRIPTION
**Pull request by Abhi10arora**
Changes made in 5 files where Imu data was taken through the topic /varun/sensors/imu/yaw. Changed the subscribed topic to /mavros/imu/data which receives data from pixhawk. It receives quateranion data which is converted into yaw in degrees.

### CODE REVIEW

**Comment by Abhi10arora** [comment]
Changes made in the script.sh file to install mavros and mavlink and their dependencies as given in the mavros installation process as given in PX4 Developer's Guide.
Also, changes are made in build.sh file to compile six mavros packages using catkin_make_isolated.

**Comment by Mayankm96** [comment]
@Abhi10arora I see you are relying on `catkin build` to build the mavros packages. As per the README [here](https://github.com/mavlink/mavros/blob/master/mavros/README.md#binary-installation-deb), it states that there is debian installation support for these packages, and you do not need to build from source. Run the following command, as suggested there, and see if it works or not:
```bash 
# To install binaries
sudo apt-get install ros-kinetic-mavros ros-kinetic-mavros-extras
# To install datasets
wget https://raw.githubusercontent.com/mavlink/mavros/master/mavros/scripts/install_geographiclib_datasets.sh
./install_geographiclib_datasets.sh
```

**Comment by Mayankm96** [comment]
@Abhi10arora I am waiting for these changes to happen.

**Comment by Abhi10arora** [comment]
@Mayankm96 binary installation worked!! Earlier i didn't checked the git repo. I'll make the changes in the documentation and other files and in the nuc.
Still i have to test something else after which i will make the documentation.

**Comment by Abhi10arora** [comment]
@Mayankm96 made changes in the Readme.md file, **build.sh** and **setup.sh** files as per the debian installation.

**Comment by Abhi10arora** [comment]
@Mayankm96 i have deleted the older code of navstik and added a file for calculating yaw from pixhawk. The other files in other layers is same as in auv2016 repo. So, overall only hardware layer is changed for pixhawk.

**Comment by Mayankm96** [comment]
We still need to fix the different build issues but I am merging this for now.

**Pull request merged**
