### PR TITLE
Motion layer

### PR DESCRIPTION
**Pull request by Suryansh470**
Code with dynamic reconfiguration changes, pid algorithm changes, camera node changes etc.

### CODE REVIEW

**Comment by Mayankm96** [comment]
* Remove commented lines of code if not required. Comments at the right places instead. 
* Resolve conflict in `README.md`

**Comment by Suryansh470** [comment]
The commented lines for most nodes are an auxiliary code just required during our testing phase of PIDs and motion .... they will be removed prior to the competition but till then they are quite necessary to avoid wastage of time

**Comment by Mayankm96** [comment]
@Suryansh470 , the codes can be made a lot better and cleaner if you begin to use OOP concepts (like classes) to write the various nodes. A particular emphasis on the [arduino node](https://github.com/Suryansh470/auv2017/blob/6a0167d1097ab6d26d76fcb70d6dfaed4edaf238/hardware_layer/hardware_arduino/src/arduino_node.cpp) in which we can simplify it by creating a class named `thruster` which has the appropriate data and methods in it. 

Why is the launch file [here](https://github.com/Suryansh470/auv2017/blob/6a0167d1097ab6d26d76fcb70d6dfaed4edaf238/hardware_layer/hardware_arduino/launch/hardware_nodes.launch) is in the hardware_arduino package while it is calling a node from the hardware_camera package?

What exactly is the purpose of the [`vid_pub`](https://github.com/Suryansh470/auv2017/blob/6a0167d1097ab6d26d76fcb70d6dfaed4edaf238/hardware_layer/hardware_camera/src/vid_pub.cpp) node? You can also look into the [`usb_cam`](http://wiki.ros.org/usb_cam) and [uvc_camera](http://wiki.ros.org/uvc_camera) packages. They use nodelets which makes it faster to send images across nodes.

A few extra coments on what exactly the classes in [here](https://github.com/Suryansh470/auv2017/blob/6a0167d1097ab6d26d76fcb70d6dfaed4edaf238/motion_library_layer/motion_forward/src/forward.cpp) and node [this](https://github.com/Suryansh470/auv2017/blob/6a0167d1097ab6d26d76fcb70d6dfaed4edaf238/motion_library_layer/motion_forward/src/forwardTest.cpp) do would help a lot to understand the code.

Use structures instead of the following:
```
p_param=config.p;
i_param=config.i;
d_param=config.d;
band_param=config.band;
```
Also fix the issue with `README.md`. There is a merge conflict occuring.

Let me know when you have some results of the tuning of the thrusters.

**Comment by Mayankm96** [comment]
@Suryansh470 In case there are scripts which are only required during test time, make test packages accordingly which we can use, instead of having to delete the lines.

**Comment by Mayankm96** [comment]
@Suryansh470 Please make the changes in this as soon as possible. I need to close the pending pull requests.

**Comment by Mayankm96** [comment]
Closing this pull request since it has become too old, and there are merge conflicts which need to be resolved. Please send in a new one once it's completed and is working.

**Pull request closed without merging**
