### PR TITLE
removed all the garbage in the code, replaced all unnecessary comments

### PR DESCRIPTION
**Pull request by ksakash**
@Mayankm96 , removed all the ``` cv::WaitKey()``` and replaced all the ```cv::imshow()``` by publishing the image on another topic instead and replaced all the unnecessary comments

### CODE REVIEW

**Comment by Mayankm96** [comment]
@ksakash see above that there is a merge conflict occurring in the README.md file.

**Comment by ksakash** [comment]
@Mayankm96, added two libraries `lib.hpp` and `pre_processing.h`, added  `dump.yaml` to save all the parameters from dynamic reconfiguration. `pre_processing.h` contains all the common functions used in all the tasks under the namespace `pre_processing`. Changed the `buoy_detection` code to the three buoy task accordingly. Also, felt no need to make a special class for doing the task specific things, for which the `task_handler_layer` is made, to handle all the task related things separately.

**Comment by Mayankm96** [comment]
@ksakash I didn't get the time yet to run the package on my system. I went through your code briefly and noticed that there are inconsistencies in the naming conventions and code practice that has to be followed by the rest of the code. Check out the [guide](https://github.com/AUV-IITK/auv2017/wiki) to get to know more. 

Also you need to comment the code in several places for better understanding in future. The dynamic config file seems to have a lot of variables present. You could possible name the variables in a better way like say `red` instead of `r` or at least put comments over what each variable does. I'll look into the classes sometime this week, but till then you need to clean the code.  The post [here](https://dev.to/barryosull/cleaning-up-your-codebase-with-a-clean-architecture) specifies what is meant by writing clean and good quality code. I hope you find it useful. 

Catch me sometime this week so that we can discuss. :)

**Comment by Mayankm96** [comment]
@ksakash Is this complete? Please complete this ASAP as I need to close pending pull requests.

**Comment by ksakash** [comment]
@Mayankm96 , from point of view of image processing, it is done. The node can detect all the three buoys and send all the coordinates related to it but inorder for the code to be fully operational we need to make changes in `buoy_client` and `buoy_server`.

**Comment by Mayankm96** [comment]
I am merging this for now. Would see how the testing goes with it.

**Pull request merged**
